### ISSUE TITLE
It is No ok for this Picture

### ISSUE THREAD

**Issue by Mase9527** [pcolton/potrace#4]
![lena](https://user-images.githubusercontent.com/20309676/118472412-6592b900-b73b-11eb-8a97-8635400ace67.png)

**Comment by Mase9527** [comment]
![Simulator Screen Shot - iPhone 11 - 2021-05-17 at 18 13 24](https://user-images.githubusercontent.com/20309676/118472643-a12d8300-b73b-11eb-827c-90dd59f78bfd.png)
This effect is not very good

**Comment by pcolton** [comment]
See the FAQ here http://potrace.sourceforge.net/faq.html , but specifically the question 'How can I improve the quality of the output of Potrace?'. Your input image is probably too high resolution. My version is a 100% port of the original, so everything in the original applies here.

**Comment by Mase9527** [comment]
> See the FAQ here http://potrace.sourceforge.net/faq.html , but specifically the question 'How can I improve the quality of the output of Potrace?'. Your input image is probably too high resolution. My version is a 100% port of the original, so everything in the original applies here.

i see，thanks。
